// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class SdfghjklTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void sdfghjkl() {
    driver.get("https://www.toptal.com/");
    driver.manage().window().setSize(new Dimension(1920, 1046));
    {
      WebElement element = driver.findElement(By.linkText("Community"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.linkText("Apply as a Freelancer")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("span:nth-child(2)"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    assertThat(driver.getTitle(), is("Join as a Freelancer | Toptal"));
    assertThat(driver.findElement(By.cssSelector(".modal-content-header")).getText(), is("Apply to Join\\\\nthe World\\\'s Top Talent Network"));
    driver.findElement(By.cssSelector(".has-default_value")).click();
    driver.findElement(By.cssSelector(".is-active > .custom_select-options_item_text")).click();
    driver.findElement(By.id("talent_create_applicant_full_name")).click();
    driver.findElement(By.id("talent_create_applicant_full_name")).sendKeys("First Last");
    driver.findElement(By.id("talent_create_applicant_email")).sendKeys("hello@someone.com");
    driver.findElement(By.id("talent_create_applicant_password")).sendKeys("abc");
    driver.findElement(By.id("talent_create_applicant_password_confirmation")).sendKeys("abc");
    driver.findElement(By.id("save_new_talent_create_applicant")).click();
    assertThat(driver.findElement(By.cssSelector(".error")).getText(), is("Password must be at least 6 characters"));
  }
}
